/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;



/**
 *
 * @author Swiper
 */
public class customerHistory extends javax.swing.JFrame {
    //private JTable tblHistory;
    private String loggedInCustomerID;   // store logged in customer ID
    
    private DefaultTableModel model;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(customerHistory.class.getName());

    /**
     * Creates new form customerHistory
     */
    public customerHistory(String customerID) {
        initComponents();
            this.loggedInCustomerID = customerID; // save it for filtering

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        viewhistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        viewhistory.setText("View History");
        viewhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewhistoryActionPerformed(evt);
            }
        });

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "AppointmentID", "CustomerID", "DoctorID", "DoctorName", "Status", "Charge", "FromRole", "ToRole", "Message"
            }
        ));
        jScrollPane1.setViewportView(tblHistory);

        jLabel1.setText("View History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(viewhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(viewhistory)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
//        // TODO add your handling code here:
//        customerDashboard dash = new customerDashboard();
//    dash.setVisible(true);
    this.dispose();  // close current window
    }//GEN-LAST:event_btnBackActionPerformed

    private void viewhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewhistoryActionPerformed
        // TODO add your handling code here:
        // Create managers
    AppointmentFileManager apptMgr = new AppointmentFileManager("C:\\Users\\Swiper\\Docments\\NetBeansProjects\\Assignment\\appointments.txt");
    FeedbackManager fbMgr = new FeedbackManager();

    // Get data
    List<Appointment> appointments = apptMgr.readAppointments();
List<Feedback> feedbacks = fbMgr.readFeedbacks(); // you must implement this


DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
model.setRowCount(0); // clear old rows

String loggedInID = this.loggedInCustomerID;

// Loop through appointments belonging to the logged-in customer only
for (Appointment a : appointments) {
    if (a.getCustomerID().equals(loggedInID)) { // filter by customer
        boolean hasFeedback = false;

        // Find feedback(s) for this appointment
        for (Feedback f : feedbacks) {
            if (f.getAppointmentID().equals(a.getAppointmentID())) {
                hasFeedback = true;
                // Add combined row (appointment + feedback)
                model.addRow(new Object[]{
                    a.getAppointmentID(),
                    a.getCustomerID(),
                    a.getDoctorID(),
                    a.getDoctorName(),
                    a.getStatus(),
                    a.getCharge(),
                    f.getFromRole(),
                    //f.getFromID(),
                    f.getToRole(),
                    //f.getToID(),
                    f.getMessage()
                });
            }
        }

        // If appointment has no feedback, still show it (with empty feedback fields)
        if (!hasFeedback) {
            model.addRow(new Object[]{
                a.getAppointmentID(),
                a.getCustomerID(),
                a.getDoctorID(),
                a.getDoctorName(),
                a.getStatus(),
                a.getCharge(),
                "", "", "", "", "" // empty feedback fields
            });
        }
    }
}


    // Clear existing rows in JTable
//    DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
//    model.setRowCount(0);

//    // Add appointments
//    for (Appointment a : appointments) {
//        model.addRow(new Object[]{
//            a.getAppointmentID(),
//            a.getCustomerID(),
//            a.getDoctorID(),
//            a.getDoctorName(),
//            //a.getDate(),
//            //a.getTime(),
//            a.getStatus(),
//            a.getCharge()
//            //"", "", "", "", "", "" // empty feedback fields
//        });
//    }

    // Add feedbacks
    // Add feedbacks
//for (Feedback f : feedbacks) {
//    model.addRow(new Object[]{
//        f.getAppointmentID(), // so you can link it with appointment
//        f.getFromID().startsWith("C") ? f.getFromID() : "", // customer
//        f.getFromID().startsWith("D") ? f.getFromID() : "", // doctor
//        "", "", "", //"", "", // other appointment-only fields
//        //f.getFeedbackID(),
//        f.getFromRole(),
//        //f.getFromID(),
//        f.getToRole(),
//        f.getToID(),
//        f.getMessage()
//        //f.getDate()
//    });
//}

//

// Loop through appointments
//for (Appointment a : appointments) {
//    // Find feedback(s) for this appointment
//    for (Feedback f : feedbacks) {
//        if (f.getAppointmentID().equals(a.getAppointmentID())) {
//            // Add combined row
//            model.addRow(new Object[]{
//                a.getAppointmentID(),
//                a.getCustomerID(),
//                a.getDoctorID(),
//                a.getDoctorName(),
//                a.getStatus(),
//                a.getCharge(),
//                f.getFromRole(),
//                f.getFromID(),
//                f.getToRole(),
//                f.getToID(),
//                f.getMessage()
//            });
//        }
//    }
//}

    }//GEN-LAST:event_viewhistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(() -> new customerHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistory;
    private javax.swing.JButton viewhistory;
    // End of variables declaration//GEN-END:variables
}
